/**
 * Created by soul on 2015/12/24.
 */
app.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise("/");
    $stateProvider
        .state("login",{
            url:"/login",
            templateUrl:"login.html",
            controller:login
        })
        .state("index",{
            url:"/",
        })
        .state("chat",{
            url:"/chat/:roomId",
            templateUrl:"chatIndex.html",
            cache:false,
            controller:chat
        })
        .state("chatAdmin",{
            url:"/chatAdmin",
            templateUrl:"chatRoomAdmin.html",
            controller:chatAdmin
        })
        .state("chatList",{
            url:"/chatList",
            templateUrl:"chatRoomList.html",
            controller:chatList
        })
        .state("error",{
            url:"/error",
            templateUrl:"error.html",
            controller:chatError
        })
        .state("chatAdminDetail",{
            url:"/chatAdmin/:id",
            templateUrl:"chatRoomAdmin-detail.html",
            controller:chatAdminDetail
        })
        .state("userInfo",{
            url:"/userInfo/:id",
            templateUrl:"userInfo.html",
            controller:userInfo
        })
})